all error statements to stderr, highlight, cleanup python docstrings

diff --git a/match b/match
--- a/match
+++ b/match
@@ -36,12 +36,16 @@ PURPOSE="Try to match a work for defining."
 CMDNAME="$0"
 USAGE="${CMDNAME} WORD"
 HELP="${PURPOSE}\nUsage: \`${USAGE}\`"
+BRED='\e[1;31m'
+SDARK='\e[2m'
+NC='\e[0m'
 
 if [[ "$1" == '-h' ]] ; then
-  echo -e "${HELP}"
+  >&2 echo -e "${HELP}"
 	exit 0
 elif [ $# -ne 1 ] ; then
-  echo -e "${HELP}"
+  >&2 echo -e "${BRED}${CMDNAME}: error: ${NC}Invalid arguments!\n"
+  >&2 echo -e "${SDARK}${HELP}${NC}"
 	exit 2
 fi
 
diff --git a/me b/me
--- a/me
+++ b/me
@@ -37,11 +37,19 @@ CMDNAME="$0"
 USAGE="${CMDNAME}"
 HELP="${PURPOSE}\nUsage: \`${USAGE}\`"
 
+BBLACK='\e[1;30m'
+BRED='\e[1;31m'
+BWHITE='\e[1;37m'
+NC='\e[0m'
+SDARK='\e[2m'
+WHITE='\e[0;37m'
+
 if [[ "$1" == '-h' ]] ; then
-  echo -e "${HELP}"
+  >&2 echo -e "${HELP}"
 	exit 0
 elif [ $# -ne 0 ] ; then
-  echo -e "${HELP}"
+  >&2 echo -e "${BRED}${CMDNAME}: error: ${NC}Invalid arguments!\n"
+  >&2 echo -e "${SDARK}${HELP}${NC}"
 	exit 2
 fi
 
diff --git a/mktags b/mktags
--- a/mktags
+++ b/mktags
@@ -38,15 +38,18 @@ USAGE="${CMDNAME}"'
 In vim link to tag file via :set tags=./tags, then do <C-LeftMouse>, g-],
 etc, :h tags.'
 HELP="${PURPOSE}\nUsage: \`${USAGE}\`"
+BRED='\e[1;31m'
+SDARK='\e[2m'
+NC='\e[0m'
 
 if [[ "$1" == '-h' ]] ; then
-  echo -e "${HELP}"
+  >&2 echo -e "${HELP}"
 	exit 0
 elif [ $# -ne 0 ] ; then
-  echo -e "${HELP}"
+  >&2 echo -e "${BRED}${CMDNAME}: error: ${NC}Invalid arguments!\n"
+  >&2 echo -e "${SDARK}${HELP}${NC}"
 	exit 2
 fi
-
 
 CMD1='ctags -R --fields=+afiksS --extra=+q &'
 CMD2='cscope -bR &'
diff --git a/swapnames b/swapnames
--- a/swapnames
+++ b/swapnames
@@ -36,13 +36,17 @@ PURPOSE="Swap two filenames, fast method, few temp files, confirmation."
 CMDNAME="$0"
 USAGE="${CMDNAME} FILENAME1 FILENAME2"
 HELP="${PURPOSE}\nUsage: \`${USAGE}\`"
+BRED='\e[1;31m'
+SDARK='\e[2m'
+NC='\e[0m'
 
 # Use 2 arguments
 if [[ "$1" == '-h' ]] ; then
-  echo -e "${HELP}"
+  >&2 echo -e "${HELP}"
 	exit 0
 elif [ $# -ne 2 ] ; then
-  echo -e "${HELP}"
+  >&2 echo -e "${BRED}${CMDNAME}: error: ${NC}Invalid arguments!\n"
+  >&2 echo -e "${SDARK}${HELP}${NC}"
 	exit 2
 fi
 
@@ -51,13 +55,13 @@ FILE2=$(dirname $2)/$(basename $2)
 
 # Check file 1
 if [ ! -f $FILE1 -a ! -d $FILE1 ] ; then
-	echo -e "${CMDCOL}swapnames:${NC} file $FILE1 does not exist!"
+	>&2 echo -e "${CMDCOL}swapnames:${NC} file $FILE1 does not exist!"
   exit
 fi
 
 # Check file 2
 if [ ! -f $FILE2 -a ! -d $FILE2 ] ; then
-	echo -e "${CMDCOL}swapnames:${NC} file $FILE2 does not exist!"
+	>&2 echo -e "${CMDCOL}swapnames:${NC} file $FILE2 does not exist!"
   exit
 fi
 
@@ -66,4 +70,4 @@ mv $FILE1 $FILE1.$$ && \
 mv $FILE2 $FILE1 && \
 mv $FILE1.$$ $FILE2 && \
 echo -e "${CMDCOL}swapnames:${NC} swapped filenames \"$FILE1\" with \"$FILE2\"." || \
-echo -e "${CMDCOL}swapnames:${NC} failed!"
+>&2 echo -e "${CMDCOL}swapnames:${NC} failed!"
